### ISSUE TITLE
PS5 fails to build unless the TSubclassOf header is included into MDViewModel.h

### ISSUE THREAD

**Issue by Maxproz** [DoubleDeez/MDViewModel#2]
Issue only happening on PS5 for some reason, all other platforms built without hitting the error.

Adding #include "Templates/SubclassOf.h" into MDViewModelBase.h fixed the issue.

![image](https://github.com/DoubleDeez/MDViewModel/assets/18764168/b19ac496-17c5-4dd3-a7a9-4fd04291d8a2)
![image](https://github.com/DoubleDeez/MDViewModel/assets/18764168/28d8f676-7342-4dfd-bb8b-26421bfc2228)

**Comment by DoubleDeez** [comment]
oh nice find, I hit this the other day but added the include where I was including MDViewModelBase.h
