### ISSUE TITLE
Null blueprint node implemented when using UPROPERTY(BlueprintAssignable) in a MDViewModel subclass.

### ISSUE THREAD

**Issue by Maxproz** [DoubleDeez/MDViewModel#3]
The function shows up with a + icon in the viewmodel editor event graph but when you click on it to implement it in that widget it comes up as an event node called NULL and compiling that will tell you there is no reference for that function.

It does work correctly if you drag off the ViewModel changed event and promote the new viewmodel to a blueprint class member varaible. Then at the bottom left in the editor click the + icon on the event to implement it that way.

**Comment by DoubleDeez** [comment]
Which commit are you on? That was happening previously but should have been fixed as of https://github.com/DoubleDeez/MDViewModel/commit/4e4f7dff4f38ad6d7e684b5b6e2a4d4ac546d9c4

**Comment by Maxproz** [comment]
Yeah I dont have that CL ill pull down latest soon.
