### ISSUE TITLE
rare MDVM Crash on editor shutdown during cook.

### ISSUE THREAD

**Issue by Maxproz** [DoubleDeez/MDViewModel#5]
LogWindows: Error: [Callstack] 0x00007ff957129e6b UnrealEditor-MDViewModelEditor.dll!FMDViewModelEditorModule::ShutdownModule() MDViewModel\Source\MDViewModelEditor\Private\MDViewModelEditorModule.cpp:102]

Fix appears to be replacing line 102 `UnregisterCustomPropertyTypeLayout` with `UnregisterCustomClassLayout` since we register it as a ClassLayout and not a PropertyTypeLayout

**Comment by DoubleDeez** [comment]
Thanks, nice find
